from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion,uuid
class Migration(migrations.Migration):
 initial=True
 dependencies=[('tenancy','0001_initial'),('organizations','0001_initial'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
 migrations.CreateModel(name='WorkflowDefinition',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('name',models.CharField(max_length=160)),('object_type',models.CharField(max_length=80)),('version',models.PositiveIntegerField(default=1)),('is_active',models.BooleanField(default=True)),('configuration',models.JSONField(blank=True,default=dict)),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='workflow_definitions',to='tenancy.tenant'))],options={'indexes':[models.Index(fields=['tenant','object_type','is_active'],name='workflows_w_tenant__20f2a4_idx')],'constraints':[models.UniqueConstraint(fields=('tenant','name','version'),name='uq_workflow_tenant_name_version')]}),
 migrations.CreateModel(name='WorkflowState',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('code',models.CharField(max_length=80)),('name',models.CharField(max_length=160)),('is_initial',models.BooleanField(default=False)),('is_terminal',models.BooleanField(default=False)),('sort_order',models.PositiveIntegerField(default=0)),('metadata',models.JSONField(blank=True,default=dict)),('definition',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='states',to='workflows.workflowdefinition'))],options={'ordering':['sort_order','code'],'constraints':[models.UniqueConstraint(fields=('definition','code'),name='uq_workflow_state_code')]}),
 migrations.CreateModel(name='WorkflowTransition',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('code',models.CharField(max_length=80)),('name',models.CharField(max_length=160)),('required_permission_code',models.CharField(blank=True,max_length=120)),('condition',models.JSONField(blank=True,default=dict)),('actions',models.JSONField(blank=True,default=list)),('definition',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='transitions',to='workflows.workflowdefinition')),('from_state',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='outgoing_transitions',to='workflows.workflowstate')),('to_state',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='incoming_transitions',to='workflows.workflowstate'))],options={'constraints':[models.UniqueConstraint(fields=('definition','code'),name='uq_workflow_transition_code')]}),
 migrations.CreateModel(name='WorkflowInstance',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('object_type',models.CharField(max_length=80)),('object_id',models.UUIDField()),('status',models.CharField(default='active',max_length=20)),('metadata',models.JSONField(blank=True,default=dict)),('current_state',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='instances',to='workflows.workflowstate')),('definition',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='instances',to='workflows.workflowdefinition')),('organization_unit',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='workflow_instances',to='organizations.organizationunit')),('started_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='started_workflows',to=settings.AUTH_USER_MODEL)),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='workflow_instances',to='tenancy.tenant'))],options={'indexes':[models.Index(fields=['tenant','object_type','object_id'],name='workflows_w_tenant__0609a0_idx'),models.Index(fields=['tenant','current_state'],name='workflows_w_tenant__4ae518_idx')],'constraints':[models.UniqueConstraint(fields=('tenant','definition','object_type','object_id'),name='uq_workflow_instance_object')]}),
 migrations.CreateModel(name='WorkflowEvent',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('comment',models.TextField(blank=True)),('metadata',models.JSONField(blank=True,default=dict)),('actor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='workflow_events',to=settings.AUTH_USER_MODEL)),('from_state',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='workflows.workflowstate')),('instance',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='events',to='workflows.workflowinstance')),('to_state',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='+',to='workflows.workflowstate')),('transition',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='events',to='workflows.workflowtransition'))])]
