from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenancy", "0001_initial"),
    ]
    operations = [
        migrations.CreateModel(
            name="Framework",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.SlugField(max_length=120)),
                ("name", models.CharField(max_length=255)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("framework_type", models.CharField(choices=[("standard", "Standard"), ("regulation", "Regulation"), ("law", "Law"), ("maturity_model", "Maturity model"), ("internal_policy", "Internal policy"), ("questionnaire", "Questionnaire"), ("best_practice", "Best practice")], default="standard", max_length=32)),
                ("content_source", models.CharField(choices=[("built_in", "Built in"), ("imported", "Imported"), ("customer", "Customer provided"), ("internal", "Internal")], default="customer", max_length=32)),
                ("license_type", models.CharField(choices=[("public", "Public"), ("licensed", "Licensed"), ("customer_provided", "Customer provided"), ("internal", "Internal")], default="customer_provided", max_length=32)),
                ("license_metadata", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("archived", "Archived")], default="draft", max_length=24)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_frameworks", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="frameworks", to="tenancy.tenant")),
            ],
            options={"ordering": ["name", "code"]},
        ),
        migrations.CreateModel(
            name="FrameworkVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version_code", models.CharField(max_length=80)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("retirement_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("retired", "Retired")], default="draft", max_length=24)),
                ("is_locked", models.BooleanField(default=False)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_framework_versions", to=settings.AUTH_USER_MODEL)),
                ("framework", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="frameworks.framework")),
            ],
            options={"ordering": ["framework__name", "-created_at"]},
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=160)),
                ("title", models.TextField()),
                ("body", models.TextField(blank=True)),
                ("guidance", models.TextField(blank=True)),
                ("assessable", models.BooleanField(default=True)),
                ("mandatory", models.BooleanField(default=True)),
                ("weight", models.DecimalField(decimal_places=3, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ("sort_order", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("framework_version", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="requirements", to="frameworks.frameworkversion")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="frameworks.requirement")),
            ],
            options={"ordering": ["sort_order", "code"]},
        ),
        migrations.CreateModel(
            name="RequirementTranslation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("language", models.CharField(max_length=12)),
                ("title", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("guidance", models.TextField(blank=True)),
                ("requirement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="translations", to="frameworks.requirement")),
            ],
            options={"ordering": ["language"]},
        ),
        migrations.CreateModel(
            name="RequirementMapping",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("mapping_type", models.CharField(choices=[("exact", "Exact"), ("strong", "Strong"), ("partial", "Partial"), ("related", "Related"), ("weak", "Weak")], default="related", max_length=16)),
                ("strength", models.DecimalField(decimal_places=4, default=0.5, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ("confidence", models.DecimalField(decimal_places=4, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ("source_type", models.CharField(choices=[("manual", "Manual"), ("imported", "Imported"), ("ai", "AI"), ("vendor", "Vendor provided")], default="manual", max_length=16)),
                ("rationale", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_requirement_mappings", to=settings.AUTH_USER_MODEL)),
                ("source_requirement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outgoing_mappings", to="frameworks.requirement")),
                ("target_requirement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="incoming_mappings", to="frameworks.requirement")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="requirement_mappings", to="tenancy.tenant")),
            ],
            options={"ordering": ["source_requirement__code", "target_requirement__code"]},
        ),
        migrations.AddConstraint(model_name="framework", constraint=models.UniqueConstraint(fields=("tenant", "code"), name="uq_framework_tenant_code")),
        migrations.AddConstraint(model_name="framework", constraint=models.UniqueConstraint(condition=models.Q(tenant__isnull=True), fields=("code",), name="uq_framework_global_code")),
        migrations.AddIndex(model_name="framework", index=models.Index(fields=["tenant", "status"], name="fw_tenant_status_idx")),
        migrations.AddIndex(model_name="framework", index=models.Index(fields=["code", "status"], name="fw_code_status_idx")),
        migrations.AddConstraint(model_name="frameworkversion", constraint=models.UniqueConstraint(fields=("framework", "version_code"), name="uq_framework_version_code")),
        migrations.AddIndex(model_name="frameworkversion", index=models.Index(fields=["framework", "status", "is_locked"], name="fwver_status_lock_idx")),
        migrations.AddConstraint(model_name="requirement", constraint=models.UniqueConstraint(fields=("framework_version", "code"), name="uq_requirement_version_code")),
        migrations.AddIndex(model_name="requirement", index=models.Index(fields=["framework_version", "parent", "sort_order"], name="req_ver_parent_sort_idx")),
        migrations.AddIndex(model_name="requirement", index=models.Index(fields=["framework_version", "assessable"], name="req_ver_assess_idx")),
        migrations.AddConstraint(model_name="requirementtranslation", constraint=models.UniqueConstraint(fields=("requirement", "language"), name="uq_requirement_translation_language")),
        migrations.AddConstraint(model_name="requirementmapping", constraint=models.CheckConstraint(condition=~models.Q(source_requirement=models.F("target_requirement")), name="ck_mapping_source_not_target")),
        migrations.AddConstraint(model_name="requirementmapping", constraint=models.UniqueConstraint(fields=("tenant", "source_requirement", "target_requirement"), name="uq_tenant_requirement_mapping")),
        migrations.AddIndex(model_name="requirementmapping", index=models.Index(fields=["tenant", "mapping_type"], name="map_tenant_type_idx")),
        migrations.AddIndex(model_name="requirementmapping", index=models.Index(fields=["tenant", "source_type"], name="map_tenant_source_idx")),
    ]
