from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):
    initial=True
    dependencies=[('tenancy','0001_initial'),('organizations','0001_initial'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='AIProviderConfig',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('name',models.CharField(max_length=120)),('provider_type',models.CharField(choices=[('openai_compatible','OpenAI-compatible'),('ollama','Ollama'),('vllm','vLLM'),('private','Private endpoint'),('mock','Mock/Test')],max_length=32)),('base_url',models.URLField(blank=True,max_length=500)),('model_name',models.CharField(max_length=160)),('secret_env_var',models.CharField(blank=True,help_text='Environment variable containing the provider API key. Secrets are never persisted here.',max_length=120)),('is_active',models.BooleanField(default=True)),('is_default',models.BooleanField(default=False)),('allow_confidential',models.BooleanField(default=False)),('configuration',models.JSONField(blank=True,default=dict)),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='ai_provider_configs',to='tenancy.tenant'))],options={'indexes':[models.Index(fields=['tenant','is_active','is_default'],name='ai_gateway_a_tenant__92ad0d_idx')],'constraints':[models.UniqueConstraint(fields=('tenant','name'),name='uq_ai_provider_tenant_name')]}),
        migrations.CreateModel(name='AIInteraction',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('capability',models.CharField(max_length=80)),('classification',models.CharField(default='internal',max_length=24)),('input_summary',models.TextField(blank=True)),('context_manifest',models.JSONField(blank=True,default=dict)),('output',models.JSONField(blank=True,default=dict)),('confidence',models.DecimalField(blank=True,decimal_places=4,max_digits=5,null=True)),('status',models.CharField(choices=[('pending','Pending'),('completed','Completed'),('failed','Failed')],default='pending',max_length=16)),('error',models.TextField(blank=True)),('provider',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='interactions',to='ai_gateway.aiproviderconfig')),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='ai_interactions',to='tenancy.tenant')),('user',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='ai_interactions',to=settings.AUTH_USER_MODEL))],options={'indexes':[models.Index(fields=['tenant','capability','created_at'],name='ai_gateway_a_tenant__453503_idx'),models.Index(fields=['tenant','status'],name='ai_gateway_a_tenant__c4c099_idx')]}),
        migrations.CreateModel(name='AISuggestion',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('object_type',models.CharField(blank=True,max_length=80)),('object_id',models.UUIDField(blank=True,null=True)),('suggestion_type',models.CharField(max_length=80)),('proposed_value',models.JSONField(default=dict)),('confidence',models.DecimalField(blank=True,decimal_places=4,max_digits=5,null=True)),('status',models.CharField(choices=[('pending','Pending'),('accepted','Accepted'),('modified','Modified'),('rejected','Rejected')],default='pending',max_length=16)),('reviewed_at',models.DateTimeField(blank=True,null=True)),('review_comment',models.TextField(blank=True)),('interaction',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='suggestions',to='ai_gateway.aiinteraction')),('reviewed_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='reviewed_ai_suggestions',to=settings.AUTH_USER_MODEL)),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='ai_suggestions',to='tenancy.tenant'))],options={'indexes':[models.Index(fields=['tenant','status','created_at'],name='ai_gateway_a_tenant__51bd42_idx'),models.Index(fields=['tenant','object_type','object_id'],name='ai_gateway_a_tenant__777be6_idx')]}),
        migrations.CreateModel(name='KnowledgeChunk',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('source_type',models.CharField(max_length=60)),('source_id',models.UUIDField(blank=True,null=True)),('title',models.CharField(blank=True,max_length=255)),('content',models.TextField()),('content_hash',models.CharField(db_index=True,max_length=64)),('token_count',models.PositiveIntegerField(default=0)),('classification',models.CharField(default='internal',max_length=24)),('metadata',models.JSONField(blank=True,default=dict)),('organization_unit',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='knowledge_chunks',to='organizations.organizationunit')),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='knowledge_chunks',to='tenancy.tenant'))],options={'indexes':[models.Index(fields=['tenant','source_type','source_id'],name='ai_gateway_k_tenant__331fac_idx'),models.Index(fields=['tenant','organization_unit'],name='ai_gateway_k_tenant__ca264b_idx')],'constraints':[models.UniqueConstraint(fields=('tenant','content_hash'),name='uq_knowledge_chunk_tenant_hash')]})
    ]
