from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL),('tenancy','0001_initial'),('organizations','0001_initial')]
    operations=[
        migrations.CreateModel(name='Evidence',fields=[
            ('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('title',models.CharField(max_length=255)),('description',models.TextField(blank=True)),('evidence_type',models.CharField(choices=[('file','File'),('url','URL'),('text','Text'),('screenshot','Screenshot'),('report','Report'),('log','Log'),('configuration','Configuration'),('other','Other')],default='file',max_length=24)),('source',models.CharField(blank=True,max_length=255)),('collected_at',models.DateTimeField(blank=True,null=True)),('valid_until',models.DateTimeField(blank=True,null=True)),('classification',models.CharField(choices=[('public','Public'),('internal','Internal'),('confidential','Confidential'),('secret','Secret')],default='internal',max_length=20)),('storage_key',models.CharField(blank=True,max_length=500)),('original_filename',models.CharField(blank=True,max_length=255)),('mime_type',models.CharField(blank=True,max_length=160)),('size',models.BigIntegerField(default=0)),('sha256',models.CharField(blank=True,max_length=64)),('url',models.URLField(blank=True)),('text_content',models.TextField(blank=True)),('metadata',models.JSONField(blank=True,default=dict)),
            ('organization_unit',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='evidence',to='organizations.organizationunit')),('owner',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='owned_evidence',to=settings.AUTH_USER_MODEL)),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='evidence',to='tenancy.tenant'))]),
        migrations.CreateModel(name='EvidenceLink',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('object_type',models.CharField(max_length=60)),('object_id',models.UUIDField()),('relation_type',models.CharField(choices=[('supports','Supports'),('proves','Proves'),('references','References'),('generated_from','Generated from')],default='supports',max_length=24)),('evidence',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='links',to='evidence.evidence')),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='evidence_links',to='tenancy.tenant'))]),
        migrations.AddConstraint(model_name='evidencelink',constraint=models.UniqueConstraint(fields=('tenant','evidence','object_type','object_id','relation_type'),name='uq_evidence_object_link')),
        migrations.AddIndex(model_name='evidence',index=models.Index(fields=['tenant','organization_unit','classification'],name='evidence_scope_class_idx')),migrations.AddIndex(model_name='evidence',index=models.Index(fields=['tenant','owner','classification'],name='evidence_owner_class_idx')),migrations.AddIndex(model_name='evidence',index=models.Index(fields=['tenant','valid_until'],name='evidence_valid_idx')),migrations.AddIndex(model_name='evidence',index=models.Index(fields=['tenant','sha256'],name='evidence_hash_idx')),migrations.AddIndex(model_name='evidencelink',index=models.Index(fields=['tenant','object_type','object_id'],name='evidence_link_obj_idx')),
    ]
