from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion,uuid
class Migration(migrations.Migration):
    initial=True
    dependencies=[("tenancy","0001_initial"),("organizations","0001_initial"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="ConnectorConfig",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("deleted_at",models.DateTimeField(blank=True,null=True)),("name",models.CharField(max_length=160)),("connector_type",models.CharField(choices=[("active_directory","Active Directory / LDAP"),("tenable","Tenable / Nessus API"),("veeam","Veeam Enterprise Manager"),("fortigate","FortiGate REST API")],max_length=32)),("base_url",models.CharField(blank=True,max_length=500)),("username_env_var",models.CharField(blank=True,max_length=120)),("secret_env_var",models.CharField(blank=True,max_length=120)),("secondary_secret_env_var",models.CharField(blank=True,max_length=120)),("verify_tls",models.BooleanField(default=True)),("is_active",models.BooleanField(default=True)),("configuration",models.JSONField(blank=True,default=dict)),("last_sync_at",models.DateTimeField(blank=True,null=True)),("last_status",models.CharField(blank=True,max_length=24)),("last_error",models.TextField(blank=True)),("organization_unit",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="connector_configs",to="organizations.organizationunit")),("tenant",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="connector_configs",to="tenancy.tenant"))],options={"indexes":[models.Index(fields=["tenant","connector_type","is_active"],name="connectors_t_tenant__pilot_idx")],"constraints":[models.UniqueConstraint(fields=("tenant","name"),name="uq_connector_tenant_name")] }),
        migrations.CreateModel(name="ConnectorRun",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("deleted_at",models.DateTimeField(blank=True,null=True)),("status",models.CharField(choices=[("running","Running"),("succeeded","Succeeded"),("failed","Failed")],default="running",max_length=16)),("started_at",models.DateTimeField(auto_now_add=True)),("finished_at",models.DateTimeField(blank=True,null=True)),("summary",models.JSONField(blank=True,default=dict)),("error",models.TextField(blank=True)),("connector",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="runs",to="connectors.connectorconfig")),("triggered_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="connector_runs",to=settings.AUTH_USER_MODEL))],options={"indexes":[models.Index(fields=["connector","status","started_at"],name="connectors_c_connect_pilot_idx")]})
    ]
