from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL),('tenancy','0001_initial'),('organizations','0001_initial'),('assessments','0001_initial'),('frameworks','0001_initial'),('controls','0001_initial'),('risks','0001_initial')]
    operations=[
        migrations.CreateModel(name='Finding',fields=[
            ('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('finding_type',models.CharField(choices=[('non_conformity','Non-conformity'),('observation','Observation'),('weakness','Weakness'),('opportunity','Opportunity for improvement')],default='non_conformity',max_length=24)),('title',models.CharField(max_length=255)),('description',models.TextField(blank=True)),('severity',models.CharField(choices=[('low','Low'),('medium','Medium'),('high','High'),('critical','Critical')],default='medium',max_length=16)),('root_cause',models.TextField(blank=True)),('due_date',models.DateField(blank=True,null=True)),('status',models.CharField(choices=[('open','Open'),('in_remediation','In remediation'),('verification','Verification'),('closed','Closed'),('accepted','Accepted')],default='open',max_length=24)),('closed_at',models.DateTimeField(blank=True,null=True)),('closure_comment',models.TextField(blank=True)),('metadata',models.JSONField(blank=True,default=dict)),
            ('assessment_item',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='findings',to='assessments.assessmentitem')),('closed_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='closed_findings',to=settings.AUTH_USER_MODEL)),('control_implementation',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='findings',to='controls.controlimplementation')),('organization_unit',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='findings',to='organizations.organizationunit')),('owner',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='owned_findings',to=settings.AUTH_USER_MODEL)),('requirement',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='findings',to='frameworks.requirement')),('risk',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='findings',to='risks.risk')),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='findings',to='tenancy.tenant'))]),
        migrations.AddIndex(model_name='finding',index=models.Index(fields=['tenant','organization_unit','status'],name='finding_scope_status_idx')),migrations.AddIndex(model_name='finding',index=models.Index(fields=['tenant','owner','due_date'],name='finding_owner_due_idx')),migrations.AddIndex(model_name='finding',index=models.Index(fields=['tenant','severity','status'],name='finding_severity_idx')),
    ]
