from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL),('tenancy','0001_initial'),('organizations','0001_initial'),('frameworks','0001_initial')]
    operations=[
        migrations.CreateModel(name='Assessment',fields=[
            ('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),
            ('title',models.CharField(max_length=255)),('assessment_type',models.CharField(choices=[('compliance','Compliance'),('maturity','Maturity'),('internal','Internal assessment'),('self','Self assessment')],default='compliance',max_length=24)),('start_date',models.DateField(blank=True,null=True)),('due_date',models.DateField(blank=True,null=True)),('status',models.CharField(choices=[('draft','Draft'),('in_progress','In progress'),('in_review','In review'),('completed','Completed'),('cancelled','Cancelled')],default='draft',max_length=24)),('overall_score',models.DecimalField(blank=True,decimal_places=3,max_digits=7,null=True)),('progress_percent',models.DecimalField(decimal_places=3,default=0,max_digits=7,validators=[django.core.validators.MinValueValidator(0),django.core.validators.MaxValueValidator(100)])),('metadata',models.JSONField(blank=True,default=dict)),
            ('framework_version',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='assessments',to='frameworks.frameworkversion')),('organization_unit',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='assessments',to='organizations.organizationunit')),('owner',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='owned_assessments',to=settings.AUTH_USER_MODEL)),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='assessments',to='tenancy.tenant'))]),
        migrations.CreateModel(name='AssessmentItem',fields=[
            ('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),
            ('requirement_code_snapshot',models.CharField(max_length=160)),('requirement_title_snapshot',models.TextField()),('requirement_body_snapshot',models.TextField(blank=True)),('weight_snapshot',models.DecimalField(decimal_places=3,default=1,max_digits=8)),('status',models.CharField(choices=[('not_assessed','Not assessed'),('compliant','Compliant'),('partial','Partially compliant'),('non_compliant','Non-compliant'),('not_applicable','Not applicable'),('compensating_control','Compensating control')],default='not_assessed',max_length=28)),('score',models.DecimalField(blank=True,decimal_places=3,max_digits=7,null=True,validators=[django.core.validators.MinValueValidator(0),django.core.validators.MaxValueValidator(100)])),('maturity_level',models.DecimalField(blank=True,decimal_places=3,max_digits=7,null=True)),('applicability',models.CharField(choices=[('applicable','Applicable'),('not_applicable','Not applicable'),('undetermined','Undetermined')],default='undetermined',max_length=20)),('assessor_comment',models.TextField(blank=True)),('reviewer_comment',models.TextField(blank=True)),
            ('assessment',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='assessments.assessment')),('assigned_to',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='assigned_assessment_items',to=settings.AUTH_USER_MODEL)),('requirement',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='assessment_items',to='frameworks.requirement')),('reviewed_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='reviewed_assessment_items',to=settings.AUTH_USER_MODEL))],options={'ordering':['requirement__sort_order','requirement_code_snapshot']}),
        migrations.AddConstraint(model_name='assessmentitem',constraint=models.UniqueConstraint(fields=('assessment','requirement'),name='uq_assessment_requirement')),
        migrations.AddIndex(model_name='assessment',index=models.Index(fields=['tenant','organization_unit','status'],name='assess_tenant_scope_idx')),migrations.AddIndex(model_name='assessment',index=models.Index(fields=['tenant','owner','due_date'],name='assess_owner_due_idx')),migrations.AddIndex(model_name='assessment',index=models.Index(fields=['tenant','framework_version'],name='assess_framework_idx')),migrations.AddIndex(model_name='assessmentitem',index=models.Index(fields=['assessment','status'],name='assess_item_status_idx')),migrations.AddIndex(model_name='assessmentitem',index=models.Index(fields=['assessment','assigned_to'],name='assess_item_user_idx')),
    ]
