"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { apiFetch } from "../../../lib/api";

type Mapping={id:string;source_code:string;source_framework:string;target_code:string;target_framework:string;mapping_type:string;strength:string;confidence:string;source_type:string;approved_at?:string|null};
type Framework={id:string;code:string;name:string};
type Version={id:string;framework:string;version_code:string};
type Req={id:string;code:string;title:string;children?:Req[]};
function flatten(nodes:Req[]):Req[]{return nodes.flatMap(n=>[n,...flatten(n.children??[])])}

export default function CrosswalkPage(){
 const [rows,setRows]=useState<Mapping[]>([]);const [frameworks,setFrameworks]=useState<Framework[]>([]);const [versions,setVersions]=useState<Version[]>([]);
 const [sourceFw,setSourceFw]=useState("");const [targetFw,setTargetFw]=useState("");const [sourceVer,setSourceVer]=useState("");const [targetVer,setTargetVer]=useState("");const [sourceReqs,setSourceReqs]=useState<Req[]>([]);const [targetReqs,setTargetReqs]=useState<Req[]>([]);const [sourceReq,setSourceReq]=useState("");const [targetReq,setTargetReq]=useState("");const [mappingType,setMappingType]=useState("related");const [message,setMessage]=useState("");
 async function loadMappings(){const r=await apiFetch('/requirement-mappings/');if(r.ok){const b=await r.json();setRows(b.results??b)}}
 async function loadBase(){const [fr,vr]=await Promise.all([apiFetch('/frameworks/'),apiFetch('/framework-versions/')]);if(fr.ok){const b=await fr.json();setFrameworks(b.results??b)}if(vr.ok){const b=await vr.json();setVersions(b.results??b)}await loadMappings()}
 useEffect(()=>{loadBase()},[]);
 useEffect(()=>{const candidates=versions.filter(v=>v.framework===sourceFw);setSourceVer(candidates[0]?.id??"")},[sourceFw,versions]);
 useEffect(()=>{const candidates=versions.filter(v=>v.framework===targetFw);setTargetVer(candidates[0]?.id??"")},[targetFw,versions]);
 useEffect(()=>{(async()=>{if(!sourceVer){setSourceReqs([]);return}const r=await apiFetch(`/requirements/tree/?framework_version=${sourceVer}`);if(r.ok)setSourceReqs(flatten(await r.json()))})()},[sourceVer]);
 useEffect(()=>{(async()=>{if(!targetVer){setTargetReqs([]);return}const r=await apiFetch(`/requirements/tree/?framework_version=${targetVer}`);if(r.ok)setTargetReqs(flatten(await r.json()))})()},[targetVer]);
 async function create(){if(!sourceReq||!targetReq)return;const r=await apiFetch('/requirement-mappings/',{method:'POST',body:JSON.stringify({source_requirement:sourceReq,target_requirement:targetReq,mapping_type:mappingType,strength:mappingType==='exact'?'1':'0.75',confidence:'1',source_type:'manual',rationale:''})});setMessage(r.ok?'Mapping ثبت شد.':'ثبت Mapping ناموفق بود.');if(r.ok){setSourceReq('');setTargetReq('');loadMappings()}}
 async function approve(id:string){const r=await apiFetch(`/requirement-mappings/${id}/approve/`,{method:'POST',body:'{}'});if(r.ok)loadMappings()}
 return <main className="adminPage"><div className="pageHead"><div><h1>Framework Crosswalk</h1><p>رابطه بین Requirementها با Mapping Type، Strength، Confidence و منشأ قابل ممیزی.</p></div><Link className="secondaryLink" href="/frameworks">کتابخانه چارچوب‌ها</Link></div>
 <article className="panel crosswalkBuilder"><h2>Mapping جدید</h2><div className="crosswalkColumns"><div><label>Source Framework<select value={sourceFw} onChange={e=>setSourceFw(e.target.value)}><option value="">انتخاب...</option>{frameworks.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Source Version<select value={sourceVer} onChange={e=>setSourceVer(e.target.value)}>{versions.filter(v=>v.framework===sourceFw).map(v=><option key={v.id} value={v.id}>{v.version_code}</option>)}</select></label><label>Source Requirement<select value={sourceReq} onChange={e=>setSourceReq(e.target.value)}><option value="">انتخاب...</option>{sourceReqs.map(r=><option key={r.id} value={r.id}>{r.code} — {r.title}</option>)}</select></label></div><div className="mappingArrow"><select value={mappingType} onChange={e=>setMappingType(e.target.value)}><option value="exact">Exact</option><option value="strong">Strong</option><option value="partial">Partial</option><option value="related">Related</option><option value="weak">Weak</option></select><span>↔</span><button className="primary" disabled={!sourceReq||!targetReq} onClick={create}>ثبت Mapping</button></div><div><label>Target Framework<select value={targetFw} onChange={e=>setTargetFw(e.target.value)}><option value="">انتخاب...</option>{frameworks.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Target Version<select value={targetVer} onChange={e=>setTargetVer(e.target.value)}>{versions.filter(v=>v.framework===targetFw).map(v=><option key={v.id} value={v.id}>{v.version_code}</option>)}</select></label><label>Target Requirement<select value={targetReq} onChange={e=>setTargetReq(e.target.value)}><option value="">انتخاب...</option>{targetReqs.map(r=><option key={r.id} value={r.id}>{r.code} — {r.title}</option>)}</select></label></div></div>{message&&<p className="message">{message}</p>}</article>
 <article className="panel"><h2>Mappings</h2><table className="dataTable"><thead><tr><th>Source</th><th>Target</th><th>Mapping</th><th>Strength</th><th>Confidence</th><th>Source Type</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.source_framework}</b><br/><code>{r.source_code}</code></td><td><b>{r.target_framework}</b><br/><code>{r.target_code}</code></td><td>{r.mapping_type}</td><td>{Math.round(Number(r.strength)*100)}%</td><td>{Math.round(Number(r.confidence)*100)}%</td><td>{r.source_type}</td><td>{r.approved_at?<span className="successText">Approved</span>:<button onClick={()=>approve(r.id)}>تأیید</button>}</td></tr>)}</tbody></table>{!rows.length&&<p className="muted">هنوز Mapping ثبت نشده است.</p>}</article></main>
}
