from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL),('tenancy','0001_initial'),('organizations','0001_initial'),('assets','0001_initial'),('controls','0001_initial')]
    operations=[
        migrations.CreateModel(name='RiskCategory',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('code',models.SlugField(max_length=100)),('name',models.CharField(max_length=200)),('description',models.TextField(blank=True)),('parent',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='children',to='risks.riskcategory')),('tenant',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='risk_categories',to='tenancy.tenant'))]),
        migrations.CreateModel(name='RiskMethodology',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('name',models.CharField(max_length=200)),('methodology_type',models.CharField(choices=[('qualitative','Qualitative'),('semi_quantitative','Semi-quantitative'),('quantitative','Quantitative')],default='semi_quantitative',max_length=24)),('likelihood_scale',models.JSONField(default=list)),('impact_scale',models.JSONField(default=list)),('matrix',models.JSONField(blank=True,default=dict)),('thresholds',models.JSONField(default=list)),('formula',models.CharField(default='product',max_length=80)),('is_default',models.BooleanField(default=False)),('status',models.CharField(default='active',max_length=20)),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='risk_methodologies',to='tenancy.tenant'))]),
        migrations.CreateModel(name='Risk',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('code',models.CharField(max_length=100)),('title',models.CharField(max_length=255)),('scenario',models.TextField(blank=True)),('cause',models.TextField(blank=True)),('consequence',models.TextField(blank=True)),('status',models.CharField(choices=[('draft','Draft'),('open','Open'),('treatment','Treatment'),('accepted','Accepted'),('closed','Closed'),('archived','Archived')],default='draft',max_length=20)),('review_date',models.DateField(blank=True,null=True)),('metadata',models.JSONField(blank=True,default=dict)),('asset',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='risks',to='assets.asset')),('category',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='risks',to='risks.riskcategory')),('organization_unit',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='risks',to='organizations.organizationunit')),('owner',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='owned_risks',to=settings.AUTH_USER_MODEL)),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='risks',to='tenancy.tenant'))]),
        migrations.CreateModel(name='RiskEvaluation',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('evaluation_type',models.CharField(choices=[('inherent','Inherent'),('current','Current'),('residual','Residual'),('target','Target')],max_length=16)),('likelihood',models.DecimalField(decimal_places=2,max_digits=10)),('impact',models.DecimalField(decimal_places=2,max_digits=10)),('score',models.DecimalField(decimal_places=4,max_digits=14)),('level',models.CharField(max_length=40)),('evaluated_at',models.DateTimeField(default=django.utils.timezone.now)),('rationale',models.TextField(blank=True)),('evaluated_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='risk_evaluations',to=settings.AUTH_USER_MODEL)),('methodology',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='evaluations',to='risks.riskmethodology')),('risk',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='evaluations',to='risks.risk'))],options={'ordering':['-evaluated_at','-created_at']}),
        migrations.CreateModel(name='RiskControl',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('relationship_type',models.CharField(choices=[('existing','Existing control'),('treatment','Treatment control'),('compensating','Compensating control')],default='existing',max_length=20)),('control_implementation',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='risk_links',to='controls.controlimplementation')),('risk',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='control_links',to='risks.risk'))]),
        migrations.CreateModel(name='RiskTreatment',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('strategy',models.CharField(choices=[('avoid','Avoid'),('reduce','Reduce'),('transfer','Transfer'),('accept','Accept')],max_length=16)),('description',models.TextField(blank=True)),('target_date',models.DateField(blank=True,null=True)),('target_score',models.DecimalField(blank=True,decimal_places=4,max_digits=14,null=True)),('approval_status',models.CharField(choices=[('not_submitted','Not submitted'),('pending','Pending'),('approved','Approved'),('rejected','Rejected')],default='not_submitted',max_length=20)),('status',models.CharField(choices=[('draft','Draft'),('planned','Planned'),('in_progress','In progress'),('completed','Completed'),('cancelled','Cancelled')],default='draft',max_length=20)),('accepted_at',models.DateTimeField(blank=True,null=True)),('accepted_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='accepted_risk_treatments',to=settings.AUTH_USER_MODEL)),('owner',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='owned_risk_treatments',to=settings.AUTH_USER_MODEL)),('risk',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='treatments',to='risks.risk'))]),
        migrations.AddConstraint(model_name='riskcategory',constraint=models.UniqueConstraint(fields=('tenant','code'),name='uq_risk_category_tenant_code')),migrations.AddConstraint(model_name='riskcategory',constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull',True)),fields=('code',),name='uq_risk_category_global_code')),migrations.AddConstraint(model_name='riskmethodology',constraint=models.UniqueConstraint(fields=('tenant','name'),name='uq_risk_methodology_tenant_name')),migrations.AddConstraint(model_name='risk',constraint=models.UniqueConstraint(fields=('tenant','code'),name='uq_risk_tenant_code')),migrations.AddConstraint(model_name='riskcontrol',constraint=models.UniqueConstraint(fields=('risk','control_implementation'),name='uq_risk_control_implementation')),
        migrations.AddIndex(model_name='riskmethodology',index=models.Index(fields=['tenant','is_default','status'],name='risks_risk_tenant__076c98_idx')),migrations.AddIndex(model_name='risk',index=models.Index(fields=['tenant','organization_unit','status'],name='risks_risk_tenant__6aeabb_idx')),migrations.AddIndex(model_name='risk',index=models.Index(fields=['tenant','owner','review_date'],name='risks_risk_tenant__072c8b_idx')),migrations.AddIndex(model_name='riskevaluation',index=models.Index(fields=['risk','evaluation_type','evaluated_at'],name='risks_riske_risk_id_50c9fc_idx')),
    ]
