from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL),('tenancy','0001_initial'),('organizations','0001_initial')]
    operations=[migrations.CreateModel(name='Action',fields=[
        ('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('title',models.CharField(max_length=255)),('description',models.TextField(blank=True)),('priority',models.CharField(choices=[('low','Low'),('medium','Medium'),('high','High'),('critical','Critical')],default='medium',max_length=16)),('start_date',models.DateField(blank=True,null=True)),('due_date',models.DateField(blank=True,null=True)),('progress',models.PositiveSmallIntegerField(default=0)),('status',models.CharField(choices=[('todo','To do'),('in_progress','In progress'),('review','Review'),('done','Done'),('cancelled','Cancelled')],default='todo',max_length=20)),('completed_at',models.DateTimeField(blank=True,null=True)),('source_type',models.CharField(blank=True,max_length=60)),('source_id',models.UUIDField(blank=True,null=True)),('metadata',models.JSONField(blank=True,default=dict)),('organization_unit',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='actions',to='organizations.organizationunit')),('owner',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='owned_grc_actions',to=settings.AUTH_USER_MODEL)),('reviewer',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='reviewed_grc_actions',to=settings.AUTH_USER_MODEL)),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='actions',to='tenancy.tenant')),
    ]),migrations.AddIndex(model_name='action',index=models.Index(fields=['tenant','organization_unit','status'],name='actions_act_tenant__9070e1_idx')),migrations.AddIndex(model_name='action',index=models.Index(fields=['tenant','owner','due_date'],name='actions_act_tenant__8b45ba_idx')),migrations.AddIndex(model_name='action',index=models.Index(fields=['tenant','source_type','source_id'],name='actions_act_tenant__aa292d_idx'))]
