import uuid
from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[('tenancy','0001_initial'),('organizations','0001_initial'),('frameworks','0001_initial'),('controls','0001_initial'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='AuditPlan',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('title',models.CharField(max_length=255)),('period_start',models.DateField()),('period_end',models.DateField()),('status',models.CharField(default='draft',max_length=20)),('approved_at',models.DateTimeField(blank=True,null=True)),('metadata',models.JSONField(blank=True,default=dict)),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='audit_plans',to='tenancy.tenant')),('organization_unit',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='audit_plans',to='organizations.organizationunit')),('owner',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='owned_audit_plans',to=settings.AUTH_USER_MODEL)),('approved_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='approved_audit_plans',to=settings.AUTH_USER_MODEL))]),
  migrations.CreateModel(name='AuditEngagement',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('title',models.CharField(max_length=255)),('audit_type',models.CharField(default='internal',max_length=20)),('objective',models.TextField(blank=True)),('scope',models.TextField(blank=True)),('start_date',models.DateField(blank=True,null=True)),('end_date',models.DateField(blank=True,null=True)),('status',models.CharField(default='draft',max_length=20)),('conclusion',models.TextField(blank=True)),('metadata',models.JSONField(blank=True,default=dict)),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='audit_engagements',to='tenancy.tenant')),('plan',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='engagements',to='internal_audits.auditplan')),('organization_unit',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='audit_engagements',to='organizations.organizationunit')),('framework_version',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='audit_engagements',to='frameworks.frameworkversion')),('lead_auditor',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='led_audits',to=settings.AUTH_USER_MODEL)),('requirements',models.ManyToManyField(blank=True,related_name='audit_engagements',to='frameworks.requirement')),('controls',models.ManyToManyField(blank=True,related_name='audit_engagements',to='controls.controlimplementation'))]),
  migrations.CreateModel(name='AuditTeamMember',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('role',models.CharField(default='auditor',max_length=80)),('engagement',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='team_members',to='internal_audits.auditengagement')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='audit_team_memberships',to=settings.AUTH_USER_MODEL))],options={'constraints':[models.UniqueConstraint(fields=('engagement','user'),name='uq_audit_team_member')]}),
  migrations.CreateModel(name='Workpaper',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True)),('title',models.CharField(max_length=255)),('objective',models.TextField(blank=True)),('procedure',models.TextField(blank=True)),('sample',models.TextField(blank=True)),('result',models.CharField(default='not_tested',max_length=20)),('conclusion',models.TextField(blank=True)),('status',models.CharField(default='draft',max_length=20)),('reviewed_at',models.DateTimeField(blank=True,null=True)),('engagement',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='workpapers',to='internal_audits.auditengagement')),('requirement',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='audit_workpapers',to='frameworks.requirement')),('control_implementation',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='audit_workpapers',to='controls.controlimplementation')),('tester',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='tested_workpapers',to=settings.AUTH_USER_MODEL)),('reviewed_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='reviewed_workpapers',to=settings.AUTH_USER_MODEL))])
 ]
